server:
  port: 10071
  servlet:
    context-path: /stream-product
spring:
  application:
    name: stream-product
  rabbitmq:
    host: 192.168.10.252
    port: 5672
    username: admin
    password: admin
    virtual-host: whportal
  cloud:
    stream:
      bindings:
        output:
          destination: stream # 指定消息发送的目的地 在rabbitmq中，指的是发送到名称为stream的exchange中
          contentType: application/json # 指定消息的类型
        myOutput:
          destination: stream-custom
          contentType: application/json
          producer:
#            partition-key-expression: payload # 指定分区键的表达式规则 可根据消息类型灵活配置
            partition-key-expression: customPartitionKeyStrategy # 指定分区键的表达式规则 可根据消息类型灵活配置
            partition-count: 2 # 指定消息分区的数量
        myInput:
          destination: stream-custom
          contentType: application/json
#      binders: # 配置绑定器
#        defaultRabbit:
#          type: rabbit
      default-binder: rabbit
