server:
  port: 20021
  servlet:
    context-path: /product-server
spring:
  application:
    name: hystrix-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
feign:
  okhttp:
    enabled: true
  client:
    config:
      default: # 服务名 填写default表示为所有服务 或者指定某个服务 如 order
        connectTimeout: 10000 # 连接超时 10秒
        readTimeout: 20000 # 读取超时 20秒
        loggerLevel: FULL
  hystrix:
    enabled: true # 开启hystrix熔断
# 配置Ribbon
ribbon:
  okhttp:
    enabled: true
# 配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    prefer-ip-address: true # 使用IP地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 10 # 注册中心从上次接收到心跳到剔除服务的间隔  便于测试 生产环境保持默认值
    lease-renewal-interval-in-seconds: 5 # 向注册中心发送心跳的间隔 便于测试 生产环境保持默认值