server:
  port: 40001
spring:
  application:
    name: config-server
  rabbitmq:
    host: 192.168.10.252
    port: 5672
    username: admin
    password: admin
    virtual-host: whportal
  cloud:
    config:
      server:
        git:
          uri: https://github.com/whportal/spring-cloud-config.git
          default-label: master # 配置文件分支
          search-paths: config # 配置文件所在根目录
#          username:
#          password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    prefer-ip-address: true # 使用IP地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 10 # 注册中心从上次接收到心跳到剔除服务的间隔  便于测试 生产环境保持默认值
    lease-renewal-interval-in-seconds: 5 # 向注册中心发送心跳的间隔 便于测试 生产环境保持默认值
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh